services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: polarent
      POSTGRES_USER: polarent
      POSTGRES_PASSWORD: polarent
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - polarent-net

  backend:
    build: ./app/Polarent
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: polarent
      DB_PASSWORD: polarent
      CORS_ALLOWED_ORIGINS: http://localhost:8080,http://localhost:8081,http://192.168.160.25:8081
    depends_on:
      - db
    networks:
      - polarent-net

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - polarent-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - polarent-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - polarent-net

volumes:
  postgres_data:
  grafana_data:

networks:
  polarent-net:
    driver: bridge
