services:
  db:
    image: postgres:16-alpine
    container_name: polarent-db-prod
    environment:
      POSTGRES_DB: polarent
      POSTGRES_USER: polarent
      POSTGRES_PASSWORD: polarent
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - polarent-prod-net
    restart: unless-stopped

  backend:
    build: ./app/Polarent
    container_name: polarent-backend-prod
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: polarent
      DB_PASSWORD: polarent
    depends_on:
      - db
    networks:
      - polarent-prod-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: polarent-frontend-prod
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - polarent-prod-net
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  polarent-prod-net:
    driver: bridge
