services:
  db:
    image: postgres:16-alpine
    container_name: polarent-db-prod
    environment:
      POSTGRES_DB: polarent
      POSTGRES_USER: polarent
      POSTGRES_PASSWORD: polarent
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - polarent-prod-net
    restart: unless-stopped

  backend:
    build: ./app/Polarent
    container_name: polarent-backend-prod
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: polarent
      DB_PASSWORD: polarent
      CORS_ALLOWED_ORIGINS: http://localhost,http://192.168.160.25
    depends_on:
      - db
    networks:
      - polarent-prod-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: polarent-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - polarent-prod-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: polarent-prometheus-prod
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - polarent-prod-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: polarent-grafana-prod
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data_prod:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - polarent-prod-net
    restart: unless-stopped

volumes:
  postgres_data_prod:
  grafana_data_prod:

networks:
  polarent-prod-net:
    driver: bridge
